# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/ui/gui_main_window_simulator_application.ui'
#
# Created: Sat Jun  5 16:32:32 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SimulatorApplicationMainWindowGui(object):
    def setupUi(self, SimulatorApplicationMainWindowGui):
        SimulatorApplicationMainWindowGui.setObjectName("SimulatorApplicationMainWindowGui")
        SimulatorApplicationMainWindowGui.resize(505, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/LaST (Cobalt) TIFF File.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimulatorApplicationMainWindowGui.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(SimulatorApplicationMainWindowGui)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(33, 287, 441, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 30, 301, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(338, 28, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(313, 380, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/clean.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 380, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 14, 128, 128))
        self.label.setPixmap(QtGui.QPixmap("icon.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(190, 70, 291, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtGui.QFrame.Plain)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.protan = QtGui.QLineEdit(self.centralwidget)
        self.protan.setGeometry(QtCore.QRect(90, 184, 113, 20))
        self.protan.setObjectName("protan")
        self.deutan = QtGui.QLineEdit(self.centralwidget)
        self.deutan.setGeometry(QtCore.QRect(90, 230, 113, 20))
        self.deutan.setObjectName("deutan")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 233, 59, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 185, 59, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 188, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(220, 234, 61, 16))
        self.label_5.setObjectName("label_5")
        SimulatorApplicationMainWindowGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SimulatorApplicationMainWindowGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 505, 23))
        self.menubar.setObjectName("menubar")
        SimulatorApplicationMainWindowGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SimulatorApplicationMainWindowGui)
        self.statusbar.setObjectName("statusbar")
        SimulatorApplicationMainWindowGui.setStatusBar(self.statusbar)

        self.retranslateUi(SimulatorApplicationMainWindowGui)
        QtCore.QMetaObject.connectSlotsByName(SimulatorApplicationMainWindowGui)

    def retranslateUi(self, SimulatorApplicationMainWindowGui):
        SimulatorApplicationMainWindowGui.setWindowTitle(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Ferramenta de Simulação", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Imagens", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Arquivo...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Simular", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Ferramenta de Simulação", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Deutan:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "Protan:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "(0 - 100%)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SimulatorApplicationMainWindowGui", "(0 - 100%)", None, QtGui.QApplication.UnicodeUTF8))

