# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/ui/gui_correct_application_main_window.ui'
#
# Created: Sat Jun  5 16:32:33 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CorrectApplicationGui(object):
    def setupUi(self, CorrectApplicationGui):
        CorrectApplicationGui.setObjectName("CorrectApplicationGui")
        CorrectApplicationGui.resize(502, 743)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/kview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CorrectApplicationGui.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(CorrectApplicationGui)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(33, 210, 441, 171))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 70, 71, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(132, 50, 46, 14))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(230, 50, 46, 14))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(131, 70, 71, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(228, 70, 71, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(329, 70, 71, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(104, 72, 21, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(330, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(30, 110, 291, 51))
        self.label_8.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Carregar<span style=\" font-weight:600;\"> </span>os dados a partir de um arquivo</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">de Resultado.</p></body></html>")
        self.label_8.setTextFormat(QtCore.Qt.RichText)
        self.label_8.setObjectName("label_8")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(204, 72, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(302, 72, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(331, 50, 46, 14))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(403, 72, 21, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(33, 400, 211, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(49, 37, 83, 18))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(114, 37, 83, 18))
        self.radioButton_4.setObjectName("radioButton_4")
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(263, 400, 211, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_5 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(46, 37, 83, 18))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(105, 37, 83, 18))
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(33, 499, 441, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(30, 30, 301, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(338, 29, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(303, 590, 91, 23))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setText("Corrigir")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(400, 590, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 128, 128))
        self.label.setPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/kview.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 40, 331, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_11.setFrameShadow(QtGui.QFrame.Plain)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.metodo = QtGui.QComboBox(self.centralwidget)
        self.metodo.setGeometry(QtCore.QRect(110, 180, 361, 27))
        self.metodo.setObjectName("metodo")
        self.metodo.addItem("")
        self.metodo.addItem("")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 186, 67, 17))
        self.label_12.setObjectName("label_12")
        CorrectApplicationGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(CorrectApplicationGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 23))
        self.menubar.setObjectName("menubar")
        CorrectApplicationGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(CorrectApplicationGui)
        self.statusbar.setObjectName("statusbar")
        CorrectApplicationGui.setStatusBar(self.statusbar)

        self.retranslateUi(CorrectApplicationGui)
        QtCore.QMetaObject.connectSlotsByName(CorrectApplicationGui)

    def retranslateUi(self, CorrectApplicationGui):
        CorrectApplicationGui.setWindowTitle(QtGui.QApplication.translate("CorrectApplicationGui", "Ferramenta de Correção", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CorrectApplicationGui", "Resultados do Teste de Daltonismo", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setText(QtGui.QApplication.translate("CorrectApplicationGui", "90", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Daltonismo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Protan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Deutan", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_3.setText(QtGui.QApplication.translate("CorrectApplicationGui", "80", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_4.setText(QtGui.QApplication.translate("CorrectApplicationGui", "35", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_6.setText(QtGui.QApplication.translate("CorrectApplicationGui", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CorrectApplicationGui", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Arquivo...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CorrectApplicationGui", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CorrectApplicationGui", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CorrectApplicationGui", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CorrectApplicationGui", "Modelo de Cor", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("CorrectApplicationGui", "RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("CorrectApplicationGui", "LMS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("CorrectApplicationGui", "Equalização do Histograma", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Sim", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Não", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("CorrectApplicationGui", "Imagens", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Arquivo...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Ferramenta de Correção", None, QtGui.QApplication.UnicodeUTF8))
        self.metodo.setItemText(0, QtGui.QApplication.translate("CorrectApplicationGui", "Metodo 1 (Antigo)", None, QtGui.QApplication.UnicodeUTF8))
        self.metodo.setItemText(1, QtGui.QApplication.translate("CorrectApplicationGui", "Metodo 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("CorrectApplicationGui", "Metodo:", None, QtGui.QApplication.UnicodeUTF8))

