# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/ui/gui_visualizator_window_correct_application.ui'
#
# Created: Sat Jun  5 16:32:33 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_CorrectApplicationVisualizatorWindow(object):
    def setupUi(self, CorrectApplicationVisualizatorWindow):
        CorrectApplicationVisualizatorWindow.setObjectName("CorrectApplicationVisualizatorWindow")
        CorrectApplicationVisualizatorWindow.resize(771, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/xeyes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CorrectApplicationVisualizatorWindow.setWindowIcon(icon)
        self.groupBox_2 = QtGui.QGroupBox(CorrectApplicationVisualizatorWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 20, 291, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(30, 31, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 51, 221, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.rgb = QtGui.QLabel(self.groupBox_2)
        self.rgb.setGeometry(QtCore.QRect(230, 33, 46, 14))
        self.rgb.setObjectName("rgb")
        self.histograma = QtGui.QLabel(self.groupBox_2)
        self.histograma.setGeometry(QtCore.QRect(230, 53, 46, 14))
        self.histograma.setObjectName("histograma")
        self.groupBox = QtGui.QGroupBox(CorrectApplicationVisualizatorWindow)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 291, 91))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 16, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 34, 121, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 52, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.da = QtGui.QLabel(self.groupBox)
        self.da.setGeometry(QtCore.QRect(200, 16, 46, 20))
        self.da.setObjectName("da")
        self.p = QtGui.QLabel(self.groupBox)
        self.p.setGeometry(QtCore.QRect(200, 34, 46, 20))
        self.p.setObjectName("p")
        self.de = QtGui.QLabel(self.groupBox)
        self.de.setGeometry(QtCore.QRect(200, 52, 46, 20))
        self.de.setObjectName("de")
        self.n = QtGui.QLabel(self.groupBox)
        self.n.setGeometry(QtCore.QRect(200, 70, 46, 20))
        self.n.setObjectName("n")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtGui.QPushButton(CorrectApplicationVisualizatorWindow)
        self.pushButton.setGeometry(QtCore.QRect(680, 560, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtGui.QTableWidget(CorrectApplicationVisualizatorWindow)
        self.tableWidget.setGeometry(QtCore.QRect(20, 130, 731, 421))
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setIconSize(QtCore.QSize(600, 600))
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButton_2 = QtGui.QPushButton(CorrectApplicationVisualizatorWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 560, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Documents and Settings/JLee/Desktop/Icones/button-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(CorrectApplicationVisualizatorWindow)
        QtCore.QMetaObject.connectSlotsByName(CorrectApplicationVisualizatorWindow)

    def retranslateUi(self, CorrectApplicationVisualizatorWindow):
        CorrectApplicationVisualizatorWindow.setWindowTitle(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Visualizador de Imagens", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Informações sobre o Filtro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Modelo de Cor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Equalização de Histograma:", None, QtGui.QApplication.UnicodeUTF8))
        self.rgb.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.histograma.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Resultado da Ferramenta de Teste", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Daltonismo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Protan:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Deutan:", None, QtGui.QApplication.UnicodeUTF8))
        self.da.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.p.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.de.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.n.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Normalidade:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Fechar", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Imagem Original", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Imagem Corrigida", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("CorrectApplicationVisualizatorWindow", "Salvar", None, QtGui.QApplication.UnicodeUTF8))

